# Generated by Django 4.0.4 on 2022-05-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField()),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
