# Generated by Django 4.0.4 on 2022-05-04 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('que', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionNum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_num', models.IntegerField()),
            ],
        ),
    ]
