# Generated by Django 4.0.4 on 2022-05-04 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('que', '0002_questionnum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionnum',
            old_name='question_num',
            new_name='questions_num',
        ),
    ]
